//Articulo
export const OBTENER_ARTICULOS = 'OBTENER_ARTICULOS';
export const REGISTRAT_ARTICULO = 'REGISTRAT_ARTICULO';
export const OBTENER_ARTICULO = 'OBTENER_ARTICULO';
export const MODIFICAR_ARTICULO = 'MODIFICAR_ARTICULO';
export const ELIMINAR_ARTICULO = 'ELIMINAR_ARTICULO';
//Modelo
export const OBTENER_MODELOS = 'OBTENER_MODELOS';
export const REGISTRAT_MODELO = 'REGISTRAT_MODELO';
export const OBTENER_MODELO = 'OBTENER_MODELO';
export const MODIFICAR_MODELO = 'MODIFICAR_MODELO';
export const ELIMINAR_MODELO = 'ELIMINAR_MODELO';